version: '3.8'
services:
  mysql-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_USER=r00t
      - MYSQL_PASSWORD=r00t
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=unit_test
    ports:
      - "3308:3306"
    volumes: 
      - mysql-db:/var/lib/mysql

  postgres-db:
    image: postgres:14.7
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=unit_test
    ports:
      - '5438:5432'
    volumes: 
      - postgres-db:/var/lib/postgresql/data

  mongo-db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
volumes:
  mysql-db:
    driver: local
  postgres-db:
    driver: local
  mongo-db:
    driver: local